#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
page="$root/ascension.html"
model="$root/ascension-model.js"
worker="$root/ascension-worker.js"
grep -q 'CRUSH FACTORY Goal Optimizer' "$page"
grep -q '次のAscensionを最短で回す' "$page"
grep -q '寝ている間にランキングを伸ばす' "$page"
grep -q '現在保有 ▲' "$page"
grep -q '現在Prestige回数 / 25' "$page"
grep -q '必要プレステージ回数 x / 25' "$page"
grep -q 'Ingot Upgrade 現在Lv' "$page"
grep -q 'Ingot Upgrade ロードマップ' "$page"
grep -q '追加購入するIngot Upgrade' "$page"
grep -q '追加購入なし' "$page"
grep -q 'slowdownText' "$page"
grep -q '20/s維持上限' "$page"
grep -q 'slowdownLevel' "$model"
grep -q '購入フェーズ — Core / Slowdown / Auto Prestige も途中で再計画' "$page"
grep -q '購入手順（1Lv / 一括購入）を表示' "$page"
grep -q 'id="prestigeCount"' "$page"
! grep -q '次に買うべきUpgrade' "$page"
grep -q '放置する時間' "$page"
grep -q '抜きたいTotal earned' "$page"
grep -q '詳細 / 実測校正' "$page"
grep -q '通常Upgrade Auto（300▲）は解放済み' "$page"
grep -q 'Ascension直後（▲0 / Ingot Lv0）' "$page"
grep -q 'MAX_TOP_SPAWN_RATE' "$model"
grep -q 'inferTotalIngotsEarned' "$model"
grep -q 'optimizeRanking' "$model"
grep -q 'optimizeRankingIngotUpgrades' "$model"
grep -q 'phaseDepth=3' "$model"
grep -q 'beamWidth=5' "$model"
grep -q 'marginal_no_gain' "$model"
grep -q 'bulkTargets' "$model"
grep -q 'maxSupplyCappedSlowdown' "$model"
grep -q "importScripts('ascension-model.js')" "$worker"
grep -q "goal==='ranking'" "$worker"
# Internal/model-only state must not be requested from the user.
! grep -q 'id="totalEarned"' "$page"
! grep -q 'id="maxTarget"' "$page"
! grep -q 'id="oneShot"' "$page"
! grep -q 'id="dpsCalibration"' "$page"
grep -q 'href="ascension.html"' "$root/index.html"

grep -q "addEventListener('input',persistEdit)" "$page"
grep -q "addEventListener('pagehide'" "$page"
grep -q "localStorage.setItem(KEY,JSON.stringify(state))" "$page"
grep -q 'copyDiagnostic' "$page"
grep -q '診断JSONをコピー' "$page"
echo 'goal-based ascension page smoke: PASS'
