#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
page="$root/ascension.html"
model="$root/ascension-model.js"
worker="$root/ascension-worker.js"
grep -q 'CRUSH FACTORY Goal Optimizer' "$page"
grep -q 'Ascension最短' "$page"
grep -q '就寝ランキング' "$page"
grep -q 'Singularity最短' "$page"
grep -q 'id="discardedAscensions"' "$page"
grep -q 'id="maxLevelEver"' "$page"
grep -q 'id="compressionTerminalSalesPerSecond"' "$page"
grep -q 'id="compressionRarePercent"' "$page"
grep -q 'id="compressionGemLevel"' "$page"
grep -q 'id="totalCrushLog"' "$page"
grep -q '▲ INGOT' "$page"
grep -q 'PRESTIGE / 25' "$page"
grep -q 'ASCENSION A' "$page"
grep -q '<h2 id="purchaseTitle">Ingot Upgrade</h2>' "$page"
grep -q 'id="ingotPlan${i}"' "$page"
grep -q 'renderIngotPlanHints' "$page"
grep -q 'function renderRoadmapFinalResult' "$page"
grep -q 'renderRoadmapFinalResult(q)' "$page"
! grep -q 'Ingot Upgrade 現在Lv' "$page"
! grep -q 'Ingot Upgrade ロードマップ' "$page"
! grep -q 'id="ingotTargetGrid"' "$page"
grep -q '追加購入なし' "$page"
grep -q 'slowdownText' "$page"
grep -q 'Top供給' "$page"
grep -q 'slowdownLevel' "$model"
grep -q '購入タイミング・途中のCore / Slowdown変更' "$page"
grep -q 'id="prestigeCount"' "$page"
! grep -q '次に買うべきUpgrade' "$page"
grep -q '放置する時間' "$page"
grep -q '抜きたいTotal earned' "$page"
grep -q '詳細 / 実測校正' "$page"
grep -q 'id="normalAutoUpdatesPerSecond"' "$page"
grep -q 'id="applyIngotPlan"' "$page"
grep -q '購入済みとして推奨Lvを反映' "$page"
! grep -q 'id="quickStartHint"' "$page"
! grep -q 'id="normalAutoUnlocked"' "$page"
grep -q 'v.normalAutoUnlocked=true' "$page"
grep -q "heldIngots').value=fmt(state.heldIngots)" "$page"
grep -q 'displayedNumber' "$page"
! grep -q "state.goal==='ascension'&&state.normalAutoUnlocked===false" "$page"
grep -q 'VRCWはUpdateごと最大1購入' "$page"
grep -q 'id="damageBoostActive"' "$page"
grep -q 'Damage Boost ×2' "$page"
grep -q 'ランキング研究計算機 — 任意LvのHP / 必要DPS / Auto OFF比較' "$page"
grep -q 'id="calcTargetLevel"' "$page"
grep -q 'id="calcPreparedDps"' "$page"
grep -q 'Large Orichalcum HP' "$page"
grep -q '供給追従に必要な最低DPS' "$page"
grep -q 'calculateRankingTarget' "$model"
grep -q 'requiredPreparedDpsLog10' "$model"
grep -q 'normalUsedAtTarget' "$model"
grep -q '補助ツール — Auto Prestige EXPペース境界' "$page"
grep -q 'id="paceTargetLevel"' "$page"
grep -q 'id="paceSlowdown"' "$page"
grep -q 'id="paceExpMultiplier"' "$page"
grep -q 'id="paceRarePercent"' "$page"
grep -q '等速AP上限' "$page"
grep -q 'calculateExpPaceBoundary' "$model"
grep -q 'directExpPaceAtLevel' "$model"
grep -q 'positiveLog' "$page"
grep -q '通常Upgrade Autoは常に解放済みとして計算します' "$page"
grep -q 'id="currentCore"' "$page"
grep -q 'id="currentSlowdownLevel"' "$page"
grep -q 'id="compressionEnabled"' "$page"
grep -q '時空圧縮 ON' "$page"
grep -q 'id="ascendSync"' "$page"
grep -q '★ASCENDした（ゲームと同期）' "$page"
grep -q 'id="syncRecommendedState"' "$page"
grep -q 'この推奨 Core / Slowdown を現在値へ同期' "$page"
grep -q 'normalAutoUnlocked:true,coreOverrideEnabled:false' "$page"
! grep -q 'Ascension直後（▲0 / Ingot Lv0）' "$page"
grep -q 'id="uiClickRate"' "$page"
grep -q 'heroEta' "$page"
grep -q '総ETA ${seconds' "$page"
grep -q 'id="apCompare"' "$page"
grep -q 'id="compareApLevel"' "$page"
grep -q 'id="compareSlowdownLevel"' "$page"
grep -q 'evaluateAutoPrestigeSetting' "$model"
! grep -q '<span>UI操作</span>' "$page"
! grep -q '<span>Top供給</span>' "$page"
! grep -q '<span>残りPrestige run</span>' "$page"
grep -q 'id="operationGuide"' "$page"
grep -q 'で進める場合.*次の操作' "$page"
grep -q '全解除' "$page"
grep -q '手動★案は走行CoreとPrestige時Coreを別々に最適化' "$page"
grep -q '最終Prestigeは戻り操作が不要なので別Core' "$page"
grep -q 'MAX_TOP_SPAWN_RATE' "$model"
grep -q 'inferTotalIngotsEarned' "$model"
grep -q 'optimizeRanking' "$model"
grep -q 'optimizeRankingIngotUpgrades' "$model"
grep -q 'phaseDepth=3' "$model"
grep -q 'beamWidth=5' "$model"
grep -q 'marginal_no_gain' "$model"
grep -q 'bulkTargets' "$model"
grep -q 'maxSupplyCappedSlowdown' "$model"
grep -q "MODEL_REVISION='r80-runtime-20260829c'" "$model"
grep -q 'src="ascension-model.js?v=r80-runtime-20260829c"' "$page"
grep -q "importScripts('ascension-model.js'+self.location.search)" "$worker"
grep -Fq 'new Worker(`ascension-worker.js?v=${encodeURIComponent(M.MODEL_REVISION)}`)' "$page"
grep -q 'modelRevision:M.MODEL_REVISION' "$page"
grep -q 'modelRevision!==msg.modelRevision' "$worker"
grep -q "goal==='ranking'" "$worker"
grep -q "goal==='singularity'" "$worker"
grep -q 'optimizeSingularity' "$model"
grep -q 'observableUniverseBestLevel' "$model"
grep -q 'optimizeCompressionSwitchPlan' "$model"
grep -q 'Compression ON切替' "$page"
grep -q 'A0はCompression OFF' "$page"
grep -q 'この推奨購入後は、さらに投資するより▲を貯める方が速い' "$page"
grep -q '固定★ — 安定 / 放置' "$page"
grep -q '手動★ — 理論高速' "$page"
grep -q '攻略スタイル' "$page"
grep -q '代替案・計算根拠' "$page"
grep -q 'finalFixedPlan' "$page"
grep -q 'finalManualPlan' "$page"
! grep -q "fixedPlan:mode==='fixed'?plan:null" "$page"
! grep -q "manualPlan:mode==='manual'?plan:null" "$page"
grep -q 'Prestige直前' "$page"
grep -q '20 top/sを維持できる範囲だけを候補' "$page"
input_line=$(grep -n 'class="card stateCard"' "$page" | head -1 | cut -d: -f1)
purchase_line=$(grep -n 'id="purchaseCard"' "$page" | head -1 | cut -d: -f1)
result_line=$(grep -n 'id="resultTitle"' "$page" | head -1 | cut -d: -f1)
calc_line=$(grep -n 'ランキング研究計算機 — 任意LvのHP / 必要DPS / Auto OFF比較' "$page" | head -1 | cut -d: -f1)
[[ $input_line -lt $purchase_line && $purchase_line -lt $result_line && $result_line -lt $calc_line ]]
grep -q 'if(worker){worker.terminate();worker=null}' "$page"
! grep -q 'function finish(){if(worker){worker.terminate()' "$page"
# Internal/model-only state must not be requested from the user.
! grep -q 'id="totalEarned"' "$page"
! grep -q 'id="maxTarget"' "$page"
! grep -q 'id="oneShot"' "$page"
! grep -q 'id="dpsCalibration"' "$page"
grep -q 'href="ascension.html"' "$root/index.html"

grep -q "addEventListener('input',persistEdit)" "$page"
grep -q "addEventListener('pagehide'" "$page"
grep -q "localStorage.setItem(KEY,JSON.stringify(state))" "$page"
grep -q 'copyDiagnostic' "$page"
grep -q '診断JSONをコピー' "$page"
echo 'goal-based ascension page smoke: PASS'
