#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
page="$root/ascension.html"
model="$root/ascension-model.js"
worker="$root/ascension-worker.js"
grep -q 'CRUSH FACTORY Goal Optimizer' "$page"
grep -q '次のAscensionを最短で回す' "$page"
grep -q '寝ている間にランキングを伸ばす' "$page"
grep -q 'SINGULARITYを最短で終える' "$page"
grep -q 'id="discardedAscensions"' "$page"
grep -q 'id="maxLevelEver"' "$page"
grep -q 'id="compressionTerminalSalesPerSecond"' "$page"
grep -q 'id="compressionRarePercent"' "$page"
grep -q 'id="compressionGemLevel"' "$page"
grep -q 'id="totalCrushLog"' "$page"
grep -q '▲ INGOT' "$page"
grep -q 'PRESTIGE / 25' "$page"
grep -q 'ASCENSION A' "$page"
grep -q 'Ingot Upgrade 現在Lv' "$page"
grep -q 'Ingot Upgrade ロードマップ' "$page"
grep -q '追加購入するIngot Upgrade' "$page"
grep -q '追加購入なし' "$page"
grep -q 'slowdownText' "$page"
grep -q 'Top供給' "$page"
grep -q 'slowdownLevel' "$model"
grep -q '購入フェーズ — Core / Slowdown / Auto Prestige も途中で再計画' "$page"
grep -q '購入手順（1Lv / 一括購入）を表示' "$page"
grep -q 'id="prestigeCount"' "$page"
! grep -q '次に買うべきUpgrade' "$page"
grep -q '放置する時間' "$page"
grep -q '抜きたいTotal earned' "$page"
grep -q '詳細 / 実測校正' "$page"
grep -q 'id="normalAutoUpdatesPerSecond"' "$page"
grep -q 'id="applyIngotPlan"' "$page"
grep -q '推奨Lvを入力へ一括反映' "$page"
grep -q 'id="quickStartHint"' "$page"
grep -q '最適化待ち不要' "$page"
grep -q "heldIngots').value=fmt(state.heldIngots)" "$page"
grep -q 'displayedNumber' "$page"
grep -q "state.goal==='ascension'&&state.normalAutoUnlocked===false" "$page"
grep -q 'VRCWはUpdateごと最大1購入' "$page"
grep -q 'id="damageBoostActive"' "$page"
grep -q 'Damage Boost ×2' "$page"
grep -q 'ランキング研究計算機 — 任意LvのHP / 必要DPS / Auto OFF比較' "$page"
grep -q 'id="calcTargetLevel"' "$page"
grep -q 'id="calcPreparedDps"' "$page"
grep -q 'Large Orichalcum HP' "$page"
grep -q '供給追従に必要な最低DPS' "$page"
grep -q 'calculateRankingTarget' "$model"
grep -q 'requiredPreparedDpsLog10' "$model"
grep -q 'normalUsedAtTarget' "$model"
grep -q 'positiveLog' "$page"
grep -q '通常Upgrade Auto（300▲）解放済み' "$page"
grep -q 'id="currentCore"' "$page"
grep -q 'id="currentSlowdownLevel"' "$page"
grep -q 'id="ascendSync"' "$page"
grep -q '★ASCENDした（ゲームと同期）' "$page"
! grep -q 'Ascension直後（▲0 / Ingot Lv0）' "$page"
grep -q 'id="uiClickRate"' "$page"
grep -q '<span>総ETA</span>' "$page"
grep -q 'id="operationGuide"' "$page"
grep -q '<b>次の操作</b>' "$page"
grep -q '全解除' "$page"
grep -q 'Prestige直前は▲倍率だけ' "$page"
grep -q 'MAX_TOP_SPAWN_RATE' "$model"
grep -q 'inferTotalIngotsEarned' "$model"
grep -q 'optimizeRanking' "$model"
grep -q 'optimizeRankingIngotUpgrades' "$model"
grep -q 'phaseDepth=3' "$model"
grep -q 'beamWidth=5' "$model"
grep -q 'marginal_no_gain' "$model"
grep -q 'bulkTargets' "$model"
grep -q 'maxSupplyCappedSlowdown' "$model"
grep -q "importScripts('ascension-model.js')" "$worker"
grep -q "goal==='ranking'" "$worker"
grep -q "goal==='singularity'" "$worker"
grep -q 'optimizeSingularity' "$model"
grep -q 'observableUniverseBestLevel' "$model"
grep -q 'A500称号はtotalではなく' "$page"
grep -q '上に表示した追加購入を実行した後は' "$page"
grep -q '固定★（操作しない）' "$page"
grep -q '手動★再配分' "$page"
grep -q '固定★案・代替案・計算根拠' "$page"
grep -q 'Prestige直前' "$page"
grep -q '20 top/sを維持できる範囲だけを候補' "$page"
input_line=$(grep -n 'class="card stateCard"' "$page" | head -1 | cut -d: -f1)
ingot_line=$(grep -n 'Ingot Upgrade 現在Lv' "$page" | head -1 | cut -d: -f1)
purchase_line=$(grep -n 'id="purchaseCard"' "$page" | head -1 | cut -d: -f1)
result_line=$(grep -n 'id="resultTitle"' "$page" | head -1 | cut -d: -f1)
calc_line=$(grep -n 'ランキング研究計算機 — 任意LvのHP / 必要DPS / Auto OFF比較（任意）' "$page" | head -1 | cut -d: -f1)
[[ $input_line -lt $ingot_line && $ingot_line -lt $purchase_line && $purchase_line -lt $result_line && $result_line -lt $calc_line ]]
grep -q 'if(worker&&workerBusy){worker.terminate();worker=null}' "$page"
! grep -q 'function finish(){if(worker){worker.terminate()' "$page"
# Internal/model-only state must not be requested from the user.
! grep -q 'id="totalEarned"' "$page"
! grep -q 'id="maxTarget"' "$page"
! grep -q 'id="oneShot"' "$page"
! grep -q 'id="dpsCalibration"' "$page"
grep -q 'href="ascension.html"' "$root/index.html"

grep -q "addEventListener('input',persistEdit)" "$page"
grep -q "addEventListener('pagehide'" "$page"
grep -q "localStorage.setItem(KEY,JSON.stringify(state))" "$page"
grep -q 'copyDiagnostic' "$page"
grep -q '診断JSONをコピー' "$page"
echo 'goal-based ascension page smoke: PASS'
